### PR TITLE
migrate information from sugarlabs wiki

### PR DESCRIPTION
**Pull request by rdrsadhu**
This PR migrates documentation from 
1. https://wiki.sugarlabs.org/go/Activities/JClic

Steps to perform after this Pull Request gets merged:
- [ ] Redirect wiki-page 1

### CODE REVIEW

**Comment by yell0wfl4sh** [comment]
Reviewed.

Sugar Labs have developers who speak many different languages, but all means of communication is done through English also, most of the README files on Sugar Labs are now in English. Better and more impactful approach would be finding a way to translate required wiki pages to English before adding a README file. 

@quozl your views.

**Comment by quozl** [comment]
Thanks.  Interesting question.  After ten years of incidental exposure I don't find the language a problem; I can get a sense of what is said, but I would still use an automated translation if it was critical to understand.

Being able to deprecate the Wiki page is a step forward.

Further steps forward for this activity, potentially outside the migration, would be to;
* [x] keep the text and add an English translation of @AlanJAS Wiki page, or borrow text from upstream,
* [x] add link to upstream repository https://github.com/projectestac/jclic,
* [x] add link to upstream organisation project https://github.com/projectestac,
* [x] use a more detailed form of README.md, as can be seen in Browse, Speak, and Memorize,

Next step is to determine consensus on what of the above should be done before merging this pull request.

Further steps unrelated to pull request; fix the other issues that prevent this activity from working, especially https://github.com/sugarlabs/JClic/issues/3, and release.

@vipulgupta2048, mentioned so you can track consensus for checklist.

**Comment by vipulgupta2048** [comment]
> Thanks. Interesting question. After ten years of incidental exposure I don't find the language a problem; I can get a sense of what is said, but I would still use an automated translation if it was critical to understand.

After Unicode and google translate, language has never been a problem. Everyone has access to these tools now. #offtopic Here's an awesome [blog post](https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/) on it.

**Comment by vipulgupta2048** [comment]
Over the tasks you mentioned. 
1. I can't find his page on the wiki. Where does the translation have to be added from?
2. and 3. @rdrsadhu You can implement sections on your own like [credits](https://github.com/sugarlabs/JClic/blob/master/CREDITS.txt) (The repository already contains one) or How to contribute or Report Bugs of this activity. Simple stuff ([Refer ](https://github.com/sugarlabs/AEIOU/pull/9)) 
4. README.md should be self-explanatory and after so many years of documentation. I have realized that README.md is the first thing I read or look for in a repository on GitHub. I think we should implement the same idea every time the migration process takes place and not just copy from A to B. 

@rdrsadhu  Yes, here is the [checklist](https://gist.github.com/vipulgupta2048/29eb0cbb6c9d294d52d9554a30f8f724) for your reference. I have listed formats and details for most of the migration process. Please add your changes too. The more consistent we can make our PR's the easier it gets for reviewers to assess it.

@quozl  Suggestion - How about adding the README.md in both languages to the repository as separate files.

**Comment by rdrsadhu** [comment]
> Next step is to determine consensus on what of the above should be done before merging this pull request.

I agree with all the 4 suggestions

**Comment by quozl** [comment]
> > keep the text and add an English translation of @AlanJAS Wiki page, or borrow text from upstream,

> I can't find his page on the wiki. Where does the translation have to be added from?

@vipulgupta2048, the @AlanJas page on the Wiki was https://wiki.sugarlabs.org/go/Activities/JClic, and there's no translation that I know of, which is why I suggested you add one, or borrow English text from the upstream project.

For bi-lingual README.md it should be in the same file interspersed within section.  Since you only have an introduction, that's the only affected section.

**Comment by rdrsadhu** [comment]
Updated:
- [x] keep the text and add an English translation of @AlanJAS Wiki page, or borrow text from upstream,
- [x] add link to upstream repository https://github.com/projectestac/jclic,
- [x] add link to upstream organisation project https://github.com/projectestac,
- [x] use a more detailed form of README.md, as can be seen in Browse, Speak, and Memorize

**Pull request merged**
